#!/bin/bash
dirName="/home/jianbin/GeneratorV0.3"
fName="${dirName}/totResults.txt"
sName="data.c1060.dat"
dataset=(128 256 512 1024 2048 4096)
#map=(107 108 109 110 112 113 114 115 116 204 205 211 302 303 306)
#map=(107 108 109 110 112 113 114 115 116 204 205 211 302 303 306)
map=(107 108 109 110 112 113 114 115 116 204 205 211 302 303 306 407 408 409 410 412 413 414 415 416 507 508 509 510 512 513 514 515 516)
over=(v4)
iver=(vv0 vv1 vv2 vv3 vv4)

  # remove file
  if [ -f "$fName" ]; then
	rm ${fName}
  fi  
  
	# check results
	let cnt=1
	for d in ${dataset[@]}; do		
		for m in ${map[@]}; do
			cd ./${m}
			for v in ${over[@]}; do
				cd ./${v}				
				for vv in ${iver[@]}; do
					cd ./${vv}
					if [ -f "${sName}" ]; then
						head -${cnt} ${sName} | tail -1 | tr -d '[\n]'>> ${fName}	
					else
						echo -ne "0\t" >> ${fName}
					fi				
					cd ../
				done
				cd ../
			done
			cd ../
  		done	
		let cnt=${cnt}+1
		echo -ne "\n" >> ${fName}
	done


